spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
app.jwtSecret=f1P0r4V3j2w8Z7x6C5b4A3q2N1m9L8k7J6h5G4F3E2D1B0c9s8q7p6o5i4u3y2t1r0e9w8v7u6t5s4q3p2o1i0u9y8x7w6v5u4t3s2r1q0p9o8i7u6y5t4s3
app.jwtExpirationInMs=86400000 # 24 saat (24 * 60 * 60 * 1000)